services:
  - type: web
    name: ajuda-ongs
    runtime: docker
    dockerfilePath: Dockerfile.render
    dockerContext: .
    healthCheckPath: /healthz
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: LOG_CHANNEL
        value: stderr
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: sqlite
      - key: DB_DATABASE
        value: /var/www/database/database.sqlite